_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 1
epochs:
    value: 3
gradient_accumulation:
    value: 16
learning_rate:
    value: 0.0002
model_name:
    value: mistralai/Mistral-7B-Instruct-v0.2
